MyRunApp/Models/ErrorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyRunApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyRunApp/Models/Shoe.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace MyRunApp.Models
{
    public class Shoe
    {
        // EF will instruct the database to automatically generate this value
        public int ShoeId { get; set; }

        [Required(ErrorMessage = "Please enter a Brand.")]
        public string Brand { get; set; }


        [Required(ErrorMessage = "Please enter a Name.")]
        public string Name { get; set; }


        [Required(ErrorMessage = "Please enter shoe use; Road or Trail.")]
        public string Use { get; set; }


        [Required(ErrorMessage = "Pleasse enter a support Type; Neutral or Stability.")]
        public string Support { get; set; }

        //[Required(ErrorMessage = "Please enter a size.")]
        //[Range(5, 14, ErrorMessage = "Size must be between 5 and 14.")]
        //public int? Size { get; set; }


        //public string Slug =>
                //Name?.Replace(' ', '-').ToLower() + '-' + Size?.ToString();
    }
}

MyRunApp/Models/ShoeContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;


namespace MyRunApp.Models
{
    public class ShoeContext : DbContext
    {
        public ShoeContext(DbContextOptions<ShoeContext> options) : base(options) { }
        public DbSet<Shoe> Shoes { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
           

            modelBuilder.Entity<Shoe>().HasData(
                new Shoe
                {
                    ShoeId = 1,
                    Brand = "Brooks",
                    Name = "Ghost 13",
                    Use = "Road Running",
                    Support= "Neutral"
                    
                },
                  new Shoe
                  {
                      ShoeId = 2,
                      Brand = "Hoka",
                      Name = "Tennine",
                      Use = "Trail Running",
                      Support = "Stability"
                    
                  },
                  new Shoe
                  {
                      ShoeId =31,
                      Brand = "Saucany",
                      Name = "Triumph 17 LE",
                      Use = "Road Running",
                      Support = "Neutral"
                      
                  }

                );
        }
    }
}

MyRunApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyRunApp.Models;
using Microsoft.EntityFrameworkCore;



namespace MyRunApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        //public HomeController(ILogger<HomeController> logger)
        //{
        //    _logger = logger;
        //}

        public IActionResult Index()
        {
            return View();
        }

        private ShoeContext context { get; set; }

        public HomeController(ShoeContext ctx)
        {
            context = ctx;
        }
        public IActionResult Shoe()
        {
            var movies = context.Shoes.OrderBy(m => m.Name).ToList();
            return View(movies);
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}
    }
}

MyRunApp/Controllers/ShoeController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MyRunApp.Models;

namespace MyRunApp.Controllers
{
    public class ShoeController : Controller
    {
        private ShoeContext context { get; set; }

        public ShoeController(ShoeContext ctx)
        {
            context = ctx;
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Action = "Add";
            //ViewBag.Genres = context.Price.OrderBy(g => g.Name).ToList();
            return View("Edit", new Shoe());
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            //ViewBag.Genres = context.Genres.OrderBy(g => g.Name).ToList();
            var movie = context.Shoes.Find(id);
            return View(movie);
        }

        [HttpPost]
        public IActionResult Edit(Shoe shoe)
        {
            if (ModelState.IsValid)
            {
                if (shoe.ShoeId == 0)
                    context.Shoes.Add(shoe);
                else
                    context.Shoes.Update(shoe);
                context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Action = (shoe.ShoeId == 0) ? "Add" : "Edit";
               //ViewBag.Genres = context.Genres.OrderBy(g => g.Name).ToList();
                return View(shoe);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var shoe = context.Shoes.Find(id);
            return View(shoe);
        }

        [HttpPost]
        public IActionResult Delete(Shoe shoe)
        {
            context.Shoes.Remove(shoe);
            context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

MyRunApp/Views/Home/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MyRunApp/Views/Home/Contact.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MyRunApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Run PR";
}
    <div class="jumbotron shadow" style="background-color:#5A5560; border-radius:50px;">
        <div class="row">
            <div class="col-lg-12">
                <h1>
                    Run PR
                    <i class='fas fa-running' style='font-size:24px;color: #46344E'></i>
                    <i class='fas fa-running' style='font-size:36px;color: ghostwhite'></i>
                    <i class='fas fa-running' style='font-size:48px;color: #46344E'></i>
                </h1>
              
                <p class="lead">
                    Run PR is designed to help maximize your running performace. The app provides tips and tricks on speed, distance, pace and strength training. The app also provides
                    a pace calculator to help achieve your next race PR.
                </p>
            </div>
        </div>
    </div>
<div class="jumbotron shadow" style="background-color:#5A5560; border-radius:30px;">
    <div class="row">
        <div class="col-md-3">
            <h2>Control your Cadence</h2>
            <p>
                What is cadence in running? How to determine what your cadence should be.<br />
            </p>
        </div>
        <div class="col-md-3">
            <h2>All about Speed</h2>
            <p>Want to set a new PR? Expore the do's and dont's of what to do to increase your speed</p>
        </div>
        <div class="col-md-3">
            <h2>Distance</h2>
            <p>Take your running to the next mile. Learn tip and tricks to maximize your long run.</p>
        </div>
        <div class="col-md-3">
            <h2>Strength Training</h2>
            <p>Workouts designed for runners to maximize their performace. </p>
        </div>
    </div>
    <div class="row">
        <img src="~/images/runningC.jpg" alt="women running by water" asp-append-version="true"
             class="float-left img-fluid col-sm-3  shadow rounded-sm" style="width:100%;" />
        <img src="~/images/speed.jpg" alt="biking through the forest" asp-append-version="true"
             class="float-left img-fluid col-sm-3  shadow rounded-sm" style="width:100%;" />
        <img src="~/images/distance.jpg" alt="seniors walking" asp-append-version="true"
             class="float-left img-fluid col-sm-3  shadow rounded-sm" style="width:100%;" />
        <img src="~/images/weight.jpg" alt="seniors walking" asp-append-version="true"
             class="float-left img-fluid col-sm-3  shadow rounded-sm" style="width:100%;" />
    </div>
    </div>


     
    

MyRunApp/Views/Home/Shoe.cshtml
@model List<Shoe>
@{
    ViewData["Title"] = "Shoes";
}

<h2>Shoe List</h2>
<a asp-controller="Movie" asp-action="Add">Add New Shoe</a>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Brand</th>
            <th>Name</th>
            <th>Use</th>
            <th>Support</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var shoe in Model)
        {
            <tr>
                <td>@shoe.Brand
                
                <td>@shoe.Name
                
                <td>@shoe.Use
                
                <td>@shoe.Support
                <td>
                
                
                    <a asp-controller="Shoe" asp-action="Edit"
                       asp-route-id="@shoe.ShoeId">Edit</a>
                    <a asp-controller="Shoe" asp-action="Delete"
                       asp-route-id="@shoe.ShoeId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

MyRunApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DetectiveAgency</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/run.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3" style="background-color:#46344E">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Run PR</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Shoe">Shoes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Run PR - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MyRunApp/Views/Shoe.cshtml
@{
    ViewData["Title"] = "Shoe";
}

<h1>Shoe</h1>

MyRunApp/Views/Shoe/Delete.cshtml
@model Shoe
@{
    ViewBag.Title = "Delete Shoe";
}
<h2>Confirm Deletion</h2>
<h3>@Model.Brand (@Model.Name)</h3>
<form asp-action="Delete" method="post">
    <input type="hidden" asp-for="ShoeId" />
    <button type="submit" class="btn btn-primary">Delete</button> <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Cancel</a>
</form>

MyRunApp/Views/Shoe/Edit.cshtml
@model Shoe
@{
    string title = ViewBag.Action + " Shoe"; ViewBag.Title = title;
}
<h2>@ViewBag.Title</h2>
<form asp-action="Edit" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Brand">Name</label>
        <input asp-for="Brand" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Use">Use</label>
        <input asp-for="Use" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Support">Support</label>
        <input asp-for="Support" class="form-control">
    </div>
    @*<div class="form-group">
        <label asp-for="Size">Rating</label>
        <input asp-for="Size" class="form-control">
    </div>*@
    @*@<div class="form-group">
        <label asp-for="GenreId">Genre</label>
        <select asp-for="GenreId" class="form-control">
            <option value="">select a genre</option>
            @foreach (Genre g in ViewBag.Genres)
            {
                <option value="@g.GenreId">@g.Name</option>
            }
        </select>
    </div>*@
    <input type="hidden" asp-for="ShoeId" />
    <button type="submit" class="btn btn-primary">@ViewBag.Action</button>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Cancel</a>
</form>